### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addError' of undefined

### ISSUE THREAD

**Issue by jameka23** [octophus/octophus#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [octophus](https://github.com/octophus/octophus) package 0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'addError' of undefined

```
At /Users/jamekaechols/.atom/packages/octophus/lib/octophus.js:63

TypeError: Cannot read property 'addError' of undefined
    at /packages/octophus/lib/octophus.js:63:32)
    at HTMLDivElement.dispatch (/packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
    at Object.trigger (/packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4350:12)
    at /packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4901:17)
    at Function.each (/packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:374:23)
    at OpenGithubDiag.each (/packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:139:17)
    at /packages/github-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4900:15)
    at /packages/github-plus/node_modules/space-pen/lib/space-pen.js:606:19)
    at OpenGithubDiag.onConfirm (/packages/octophus/lib/dialogs/open-github-dialog.js:18:10)
    at /packages/octophus/lib/dialogs/dialog.js:51:14)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -8:00.8.0 application:add-project-folder (div.tool-panel.tree-view)
     -7:33.9.0 window:install-shell-commands (div.tool-panel.tree-view)
     -6:57.3.0 core:confirm (input.hidden-input)
     -4:53.6.0 core:paste (input.hidden-input)
     -0:46 octophus:open-repo (div.package-readme.native-key-bindings)
  8x -0:28.9.0 core:backspace (input.hidden-input)
     -0:13.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
github-notifications 0.1.2 
github-plus 1.0.0 
github-user-datatip 0.3.2 
github-utils 1.6.0 
my-github-profile 0.2.1 
octophus 0.1.1 
```

**Comment by zhongyi-tong** [comment]
@jameka23 Sorry Jameka, this project is no longer under maintenance. Atom has changed a lot since the project started. Hope you will find an alternative tool.
